version: '3'

services:

  ticketing-system:
    restart: always
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=ticketing
      - LETSENCRYPT_HOST=tiketing