version: '3'

services:

  ticketing-system:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      -"9000:9000"
    environment:
      - VIRTUAL_HOST=ticketing
      - LETSENCRYPT_HOST=tiketing