// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: auth.sql

package db

import (
	"context"
)

const loginUser = `-- name: LoginUser :one
SELECT id, role_id FROM users
WHERE username = ? and password = ?
`

type LoginUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginUserRow struct {
	ID     int32 `json:"id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (LoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, loginUser, arg.Username, arg.Password)
	var i LoginUserRow
	err := row.Scan(&i.ID, &i.RoleID)
	return i, err
}
